-- 初始化数据库表信息
-- 初始化脚本
-- 创建数据库
CREATE DATABASE IF NOT EXISTS `table_tennis_system`;
-- 用户表
CREATE TABLE CAUSUER (
		GUID VARCHAR(50) PRIMARY KEY COMMENT 'ID主键',
		USER_NAME VARCHAR(100) COMMENT '用户名，不能重复',
		PASSWORD VARCHAR(100) COMMENT '密码',
		IMG_PATH VARCHAR(200) COMMENT '用户图片路径',
		MOBILE_PHONE VARCHAR(20) COMMENT '手机号',
		GENDER INT COMMENT '性别 0 女，1 男',
		AGE INT COMMENT '年龄',
		CREATE_DATE VARCHAR(20) COMMENT '创建日期',
		CREATE_USER VARCHAR(100) COMMENT '创建用户（用户名）',
		UPDATE_DATE VARCHAR(20) COMMENT '更新日期',
		UPDATE_USER VARCHAR(100) COMMENT '更新用户（用户名）',
		STATUS INT COMMENT '是否可用 1 可用，0 不可用'
);

-- 球桌表 BALL_TABLE
CREATE TABLE BALL_TABLE(
		GUID VARCHAR(50) PRIMARY KEY COMMENT 'ID主键',
		IMG_PATH VARCHAR(200) COMMENT '图片路径',
		CODE VARCHAR(20) UNIQUE COMMENT '球桌编码(唯一)',
		ADDRESS VARCHAR(100) COMMENT '地址位置',
		DESCRIPTION VARCHAR(200) COMMENT '描述',
		CREATE_DATE VARCHAR(20) COMMENT '创建日期',
		CREATE_USER VARCHAR(100) COMMENT '创建用户（用户名）',
		UPDATE_DATE VARCHAR(20) COMMENT '更新日期',
		UPDATE_USER VARCHAR(100) COMMENT '更新用户（用户名）',
		STATUS INT COMMENT '是否可用 1 可用，0 不可用'
);
-- 用户预订表
CREATE TABLE RESERVE(
		USER_ID VARCHAR(50) COMMENT '用户id',
		TABLE_ID VARCHAR(50) COMMENT '球桌id',
		START_DATE VARCHAR(20) COMMENT '开始时间',
		USE_TIME INT COMMENT '预订时长，单位(小时)',
		PAY_AMT DECIMAL(10, 2) COMMENT '支付金额',
		BILL_ID VARCHAR(50) COMMENT '预订主单id，用于球友匹配相关功能,多个预订单会属于同一个主单',
		RESERVE_STATUS INT COMMENT '预订状态. -3 预订失败，0 预订成功，待付款，1 待匹配球友拼桌， 3 付款成功，待使用 4:已使用 6 预订取消 9 预订过期 ',
		CREATE_DATE VARCHAR(20) COMMENT '创建日期',
		CREATE_USER VARCHAR(100) COMMENT '创建用户（用户名）',
		UPDATE_DATE VARCHAR(20) COMMENT '更新日期',
		UPDATE_USER VARCHAR(100) COMMENT '更新用户（用户名）'
);

-- 消息表
CREATE TABLE MESSAGE(
		GUID VARCHAR(50) PRIMARY KEY COMMENT 'ID主键',
		USER_ID VARCHAR(50) COMMENT '用户ID',
		TEXT VARCHAR(500)  COMMENT '消息内容',
		TYPE INT COMMENT '消息类型： 1 用户消息 2 全体消息',
		CATEGORY INT COMMENT '消息类别：用于细分消息，如支付，退款，预订，预订取消（在代码中可以使用枚举类）',
		CREATE_DATE VARCHAR(20) COMMENT '创建日期',
		CREATE_USER VARCHAR(100) COMMENT '创建用户（用户名）',
		UPDATE_DATE VARCHAR(20) COMMENT '更新日期',
		UPDATE_USER VARCHAR(100) COMMENT '更新用户（用户名）'
);
