-- 增加匹配表
CREATE TABLE MATCH_INFO(
		GUID VARCHAR(50) PRIMARY KEY COMMENT '主键ID',
		BILL_RESERVE_ID VARCHAR(50) COMMENT '对应主预订单的id',
		BILL_USER_ID VARCHAR(50) COMMENT '主单用户ID',
		BILL_USER_NAME  VARCHAR(100) COMMENT '主单用户名',
		BILL_USER_OUT_TRADE_NO VARCHAR(100) COMMENT '主单用户商户订单号',
		BILL_USER_TRADE_NO VARCHAR(100) COMMENT '主单用户支付交易号',
		MATCH_USER_ID VARCHAR(50) COMMENT '匹配用户ID',
		MATCH_USER_NAME  VARCHAR(100) COMMENT '匹配用户名',
		MATCH_USER_OUT_TRADE_NO VARCHAR(100) COMMENT '匹配用户商户订单号',
		MATCH_USER_TRADE_NO VARCHAR(100) COMMENT '匹配用户支付交易号',
		LEVEL INT COMMENT '技术水平: 1 初级、2 中级、3 高级',
		BILL_REMARK VARCHAR(200) COMMENT '主单用户备注描述',
		TABLE_ID VARCHAR(50) COMMENT '球桌ID',
		TABLE_CODE VARCHAR(20) COMMENT '球桌编码',
		START_DATE VARCHAR(20) COMMENT '开始时间',
		USE_TIME INT COMMENT '预订时长，单位(小时)',
		STATUS INT COMMENT '匹配单状态： 0 正在匹配  1 预匹配，等待主单用户同意 2 匹配成功',
		CREATE_DATE VARCHAR(20) COMMENT '创建日期',
		CREATE_USER VARCHAR(100) COMMENT '创建用户（用户名）',
		UPDATE_DATE VARCHAR(20) COMMENT '更新日期',
		UPDATE_USER VARCHAR(100) COMMENT '更新用户（用户名）'
);
-- 增加计算列
ALTER TABLE MATCH_INFO
ADD COLUMN PROCESS_START_DATE VARCHAR(10) AS (SUBSTRING(START_DATE , 1, 10));
-- 增加主单用户应支付金额，匹配用户应付支付金额
ALTER TABLE MATCH_INFO
ADD COLUMN BILL_USER_NEED_PAY_AMT DECIMAL COMMENT '主单用户应支付金额';

ALTER TABLE MATCH_INFO
ADD COLUMN MATCH_USER_NEED_PAY_AMT DECIMAL COMMENT '匹配用户应支付金额';