-- 增加角色表
CREATE  TABLE ROLE(
		GUID VARCHAR(50) PRIMARY KEY COMMENT 'ID主键',
		NAME VARCHAR(100) COMMENT '角色名称',
		REMARK VARCHAR(200) COMMENT '备注'
);
-- 增加角色菜单表
CREATE  TABLE ROLE_MENU(
		GUID VARCHAR(50) PRIMARY KEY COMMENT 'ID主键',
		ROLE_ID VARCHAR(100) COMMENT '角色ID',
		MENU_ID VARCHAR(100) COMMENT '菜单ID'
);
-- 用户表增加角色id字段
ALTER TABLE CAUSUER  ADD ROLE_ID VARCHAR(50)  COMMENT '角色ID';
