-- 订单表增加用户编码字段（用户名）
ALTER TABLE RESERVE  ADD USER_NAME VARCHAR(100) COMMENT '用户名，不能重复';
-- 预订单表增加商户订单号和支付宝交易号
ALTER TABLE RESERVE  ADD TRADE_NO VARCHAR(100) COMMENT '支付宝订单交易号';
ALTER TABLE RESERVE  ADD OUT_TRADE_NO VARCHAR(100) COMMENT '商户订单号';