-- 增加候补表
CREATE TABLE CANDIDATE_RESERVE(
		GUID VARCHAR(50) PRIMARY KEY COMMENT 'ID主键',
		USER_ID VARCHAR(50) COMMENT '用户ID',
		TABLE_ID VARCHAR(50) COMMENT '球桌ID',
		START_DATE VARCHAR(20) COMMENT '开始时间',
		USE_TIME INT COMMENT '预订时长，单位(小时)'
);
-- 增加候补状态字段
ALTER TABLE CANDIDATE_RESERVE ADD STATUS INT  COMMENT '候补状态：0 候补中，1 候补成功';
-- 增加球桌编号字段
ALTER TABLE CANDIDATE_RESERVE ADD TABLE_CODE VARCHAR(20)  COMMENT '球桌编号';
-- 增加计算列
ALTER TABLE CANDIDATE_RESERVE
ADD COLUMN PROCESS_START_DATE VARCHAR(10) AS (SUBSTRING(START_DATE , 1, 10));
-- 增加创建日期字段
ALTER TABLE CANDIDATE_RESERVE ADD CREATE_DATE VARCHAR(20)  COMMENT '创建日期';
-- 增加交易金额，商户订单号，交易号字段
ALTER TABLE CANDIDATE_RESERVE  ADD	PAY_AMT DECIMAL(10, 2) COMMENT '支付金额';
ALTER TABLE CANDIDATE_RESERVE  ADD OUT_TRADE_NO VARCHAR(100) COMMENT '商户订单号';
ALTER TABLE CANDIDATE_RESERVE  ADD TRADE_NO VARCHAR(100) COMMENT '支付宝订单交易号';
-- 增加用户名
ALTER TABLE CANDIDATE_RESERVE  ADD USER_NAME VARCHAR(100) COMMENT '用户名';
