-- 球桌表增加当天开放时间和结束时间字段(用于分时段开放)
ALTER TABLE BALL_TABLE ADD START_TIME VARCHAR(8)  COMMENT '球桌当天开放时间，24小时制：HH:mm:ss';
ALTER TABLE BALL_TABLE ADD END_TIME VARCHAR(8)  COMMENT '球桌当天结束时间，24小时制：HH:mm:ss';

-- 球桌表增加基础字段  球桌基础信息优化，增加球桌品牌，地面材质，球桌完好程度
ALTER TABLE BALL_TABLE ADD BRAND VARCHAR(50)  COMMENT '球桌品牌';
ALTER TABLE BALL_TABLE ADD FLOOR_MATERIAL VARCHAR(50)  COMMENT '地面材质：如黑色地胶，瓷砖，木制';
ALTER TABLE BALL_TABLE ADD QUALITY_RATING VARCHAR(50)  COMMENT '球桌完好程度：完美，优良，破损';
