CREATE TABLE MESSAGE(
		GUID VARCHAR(50) PRIMARY KEY COMMENT 'ID主键',
	    ORIGIN_ID  VARCHAR(50) COMMENT '发送者ID',
	    ORIGIN_NAME  VARCHAR(50) COMMENT '发送者名称',
	    TARGET_ID VARCHAR(50) COMMENT '接收者ID',
	    TARGET_NAME VARCHAR(50) COMMENT '接收者名称',
	    TYPE INT COMMENT '消息类型：1 单点消息 2 全体消息',
	    CATEGORY INT COMMENT '消息类别：1 系统消息 2 用户消息',
	    VALUE VARCHAR(300)  COMMENT '消息内容',
	    CREATE_TIME VARCHAR(20) COMMENT '创建时间'
);
-- 增加已读字段
ALTER TABLE MESSAGE ADD IS_READ INT  COMMENT '消息是否已读  0 未读  1 已读';